"""your message

Revision ID: a323c28e0447
Revises: 815d7693913c
Create Date: 2026-02-25 19:02:17.423338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a323c28e0447'
down_revision = '815d7693913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
