"""your message

Revision ID: a454b6b2ff36
Revises: cfd3d4522e89
Create Date: 2026-02-25 19:47:30.042776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a454b6b2ff36'
down_revision = 'cfd3d4522e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
