"""create messages table

Revision ID: cfd3d4522e89
Revises: a323c28e0447
Create Date: 2026-02-25 19:15:30.176297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd3d4522e89'
down_revision = 'a323c28e0447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
